// file: content/manifesto.ts
import type { Locale } from "@/lib/i18n";

type ManifestoContent = {
  title: string;
  paragraphs: string[];
};

export const manifestoContent: Record<Locale, ManifestoContent> = {
  pl: {
    title: "Manifest",
    paragraphs: [
      "Liberalizm nie jest neutralną filozofią wolności, lecz ideologiczną zasłoną dla międzynarodowego spisku wymierzonego w narody i ich suwerenność. Pod hasłami pluralizmu, otwartości i praw jednostki dokonano bezprecedensowego przejęcia realnej władzy nad państwami przez struktury pozbawione zakorzenienia, odpowiedzialności i lojalności wobec jakiejkolwiek wspólnoty narodowej. Żyjemy w epoce postępującej dezorganizacji moralnej, w której zerwanie z porządkiem naturalnym i historycznym stało się normą, a nie odstępstwem. Stan ten jest rezultatem długofalowego i skoordynowanego procesu osłabiania narodów.",
      "Współczesny świat znajduje się pod wpływem międzynarodowego spisku kapitałowo-ideologicznego, tworzonego przez globalne fundusze finansowe, struktury medialne, organizacje „eksperckie”, fundacje oraz instytucje ponadnarodowe, działające poza demokratyczną kontrolą społeczeństw. Spisek ten nie funkcjonuje jako jednolita instytucja, lecz jako sieć interesów, której celem jest podporządkowanie państw narodowych logice globalnego zarządzania i zysku. Narody mają zostać sprowadzone do roli mas zarządzanych, pozbawionych realnego wpływu na własny los.",
      "Jednym z kluczowych obszarów działania tego spisku jest kultura. Sztuka przestała być wyrazem ducha narodu, jego historii i doświadczenia. Została przejęta przez zagraniczne ośrodki finansowania, dystrybucji i legitymizacji, które decydują o tym, co ma być promowane, nagradzane i obecne w przestrzeni publicznej. To, co określa się dziś mianem „kultury”, w coraz mniejszym stopniu wyrasta z narodowego dziedzictwa, a w coraz większym stanowi nośnik obcych ideologii i wzorców, mających na celu wykorzenienie społeczeństwa z własnej tożsamości. Nasza sztuka nie jest już nasza – jest importowana, narzucona i podporządkowana interesom zewnętrznym.",
      "Równie istotnym polem działania międzynarodowego spisku jest edukacja. Szkoły, które powinny pełnić funkcję wychowawczą i narodotwórczą, zostały przekształcone w narzędzie ideologicznej indoktrynacji. Pod pozorem nowoczesności i neutralności światopoglądowej dzieci i młodzież są systematycznie odrywane od własnej tradycji, historii i naturalnych norm moralnych. Programy nauczania, materiały edukacyjne oraz szkolenia kadry pedagogicznej coraz częściej powstają pod wpływem zagranicznych organizacji i ideologicznych centrów, których celem nie jest dobro narodu, lecz jego przebudowa zgodnie z globalnym projektem.",
      "Celem tego procesu jest wytworzenie społeczeństwa wykorzenionego, pozbawionego tożsamości, niezdolnego do solidarności i oporu. Człowiek oderwany od narodu, rodziny i tradycji staje się łatwym obiektem kontroli ekonomicznej i ideologicznej. Degeneracja moralna, relatywizacja wartości, rozpad autorytetów i wspólnot nie są skutkiem ubocznym współczesności, lecz elementami świadomie wykorzystywanymi przez międzynarodowy spisek jako narzędzia dominacji.",
      "Istotnym elementem tego procesu jest działalność międzynarodowej kliki, rozumianej jako wąska warstwa powiązanych ze sobą elit finansowych, medialnych, politycznych i ideologicznych, funkcjonujących poza realną kontrolą społeczną. Klika ta nie posiada demokratycznej legitymacji, a mimo to wywiera decydujący wpływ na kierunki polityki państw, narracje medialne oraz ramy dopuszczalnej debaty publicznej. To ona wyznacza granice tego, co wolno myśleć, mówić i tworzyć, stygmatyzując wszelkie przejawy sprzeciwu wobec globalnego porządku jako „ekstremizm”, „zacofanie” lub „zagrożenie”.",
      "Międzynarodowa klika posługuje się aparatem kultury masowej, edukacji, instytucji eksperckich oraz mechanizmami presji ekonomicznej, aby narzucać narodom jednolity model cywilizacyjny, sprzeczny z ich tradycją, historią i interesem. Jej celem nie jest współpraca między narodami, lecz ich trwałe osłabienie, rozbicie więzi społecznych i pozbawienie zdolności do samodzielnego działania. W takim świecie decyzje zapadają poza wspólnotami narodowymi, a odpowiedzialność zostaje rozmyta w nieprzejrzystych strukturach władzy.",
      "Narodowy integralizm stanowi całkowite odrzucenie tego porządku. Uznajemy naród za najwyższą wartość polityczną i jedyny prawomocny podmiot życia publicznego.",
      "Integralnym elementem odzyskania suwerenności narodowej jest odbudowa kontroli nad gospodarką, która w obecnym porządku została w znacznym stopniu podporządkowana interesom międzynarodowego kapitału. Gospodarka nie może funkcjonować jako autonomiczna sfera oderwana od interesu narodowego, ani jako narzędzie realizacji zysków podmiotów działających poza wspólnotą polityczną. Pozostawienie kluczowych sektorów logice nieograniczonego rynku prowadzi do utraty kontroli nad zasobami strategicznymi, uzależnienia państwa od zewnętrznych centrów decyzyjnych oraz osłabienia stabilności społecznej.",
      "Narodowy integralizm odrzuca zarówno dogmat skrajnego liberalizmu gospodarczego, jak i kolektywistyczne koncepcje socjalistyczne. Opowiadamy się za silnym, świadomym i odpowiedzialnym interwencjonizmem państwowym, którego celem jest ochrona interesu narodowego przed dominacją międzynarodowego kapitału. Państwo musi posiadać realne instrumenty regulacyjne i własnościowe umożliwiające kontrolę nad kluczowymi sektorami gospodarki, systemem finansowym, infrastrukturą oraz rynkiem pracy.",
      "Interwencjonizm nie jest zaprzeczeniem racjonalnej gospodarki, lecz warunkiem jej podporządkowania dobru wspólnemu. Bez aktywnej roli państwa gospodarka staje się narzędziem nacisku politycznego, a decyzje ekonomiczne zapadają poza granicami wspólnoty narodowej. Ograniczenie wpływu międzynarodowego kapitału, przeciwdziałanie spekulacji, ochrona rodzimej produkcji i własności oraz zapewnienie bezpieczeństwa ekonomicznego społeczeństwa są niezbędnymi elementami suwerenności państwowej.",
      "Silne państwo narodowe nie może abdykować z odpowiedzialności za kształt gospodarki. Musi ono aktywnie przeciwdziałać procesom, które prowadzą do wyzysku, destabilizacji i podporządkowania gospodarki interesom zewnętrznym. Tylko gospodarka osadzona w ramach narodowych, podporządkowana długofalowym celom wspólnoty, może stanowić fundament trwałej niezależności politycznej i społecznej.",
      "Odrzucamy prawo jakichkolwiek ponadnarodowych struktur, sieci interesów i ideologicznych projektów do ingerowania w kulturę, edukację, gospodarkę i politykę państwa narodowego. Państwo musi odzyskać pełną kontrolę nad strategicznymi obszarami życia społecznego, aby skutecznie bronić interesu narodowego.",
      "Państwo narodowe nie może pozostawać neutralne wobec procesów, które prowadzą do moralnego, kulturowego i politycznego rozkładu wspólnoty. Jego obowiązkiem jest ochrona tożsamości narodowej, porządku moralnego i suwerenności przed presją międzynarodowego spisku, niezależnie od form, pod jakimi on występuje. W relacjach międzynarodowych odrzucamy wszelkie mechanizmy podporządkowania się ponadnarodowym centrom decyzyjnym, które dążą do likwidacji państw narodowych jako realnych podmiotów historii.",
      "Narodowy integralizm jest projektem odzyskania kontroli nad własnym losem. Jest sprzeciwem wobec świata zarządzanego zza kulis, w którym narody mają zostać zastąpione przez rynki, konsumentów i bezkształtne populacje. Jest wezwaniem do odbudowy wspólnoty narodowej jako suwerennego, świadomego i moralnie zakorzenionego podmiotu politycznego.",
    ],
  },
  en: {
    title: "Manifesto",
    paragraphs: [
      "Liberalism is not a neutral philosophy of freedom, but an ideological veil for an international conspiracy directed against nations and their sovereignty. Under the slogans of pluralism, openness, and individual rights, there has been an unprecedented seizure of real power over states by structures devoid of rootedness, responsibility, and loyalty to any national community. We live in an era of advancing moral disorganization, in which breaking with the natural and historical order has become the norm rather than the exception. This condition is the result of a long-term and coordinated process of weakening nations.",
      "The contemporary world is under the influence of an international capital‑ideological conspiracy, formed by global financial funds, media structures, “expert” organizations, foundations, and supranational institutions operating beyond the democratic control of societies. This conspiracy does not function as a single institution, but as a network of interests whose aim is to subordinate nation-states to the logic of global management and profit. Nations are to be reduced to managed masses, deprived of real influence over their own fate.",
      "One of the key areas of this conspiracy’s activity is culture. Art has ceased to be an expression of the spirit of the nation, its history, and experience. It has been taken over by foreign centers of financing, distribution, and legitimization, which decide what is promoted, rewarded, and present in the public sphere. What is today described as “culture” increasingly grows less from national heritage and more as a carrier of foreign ideologies and patterns aimed at uprooting society from its own identity. Our art is no longer ours—it is imported, imposed, and subordinated to external interests.",
      "An equally important field of action for this international conspiracy is education. Schools, which should fulfill an educational and nation-forming role, have been transformed into an instrument of ideological indoctrination. Under the pretext of modernity and ideological neutrality, children and youth are systematically torn away from their own tradition, history, and natural moral norms. Curricula, educational materials, and teacher training are increasingly shaped under the influence of foreign organizations and ideological centers whose aim is not the good of the nation but its reconstruction in line with a global project.",
      "The goal of this process is to produce a society that is uprooted, devoid of identity, and incapable of solidarity and resistance. A person detached from nation, family, and tradition becomes an easy object of economic and ideological control. Moral degeneration, the relativization of values, and the collapse of authorities and communities are not side effects of modernity but elements consciously used by the international conspiracy as tools of domination.",
      "A significant element of this process is the activity of an international clique—understood as a narrow stratum of interconnected financial, media, political, and ideological elites operating beyond real social control. This clique lacks democratic legitimacy, yet exerts decisive influence on the direction of state policy, media narratives, and the boundaries of permissible public debate. It sets the limits of what one is allowed to think, say, and create, stigmatizing any opposition to the global order as “extremism,” “backwardness,” or a “threat.”",
      "The international clique uses mass culture, education, expert institutions, and mechanisms of economic pressure to impose a uniform civilizational model on nations—one contrary to their tradition, history, and interests. Its aim is not cooperation between nations but their lasting weakening, the breaking of social bonds, and depriving them of the ability to act independently. In such a world, decisions are made outside national communities, and responsibility is dissolved within opaque structures of power.",
      "National integralism constitutes a complete rejection of this order. We recognize the nation as the highest political value and the only legitimate subject of public life.",
      "An integral element of restoring national sovereignty is rebuilding control over the economy, which in the current order has been significantly subordinated to the interests of international capital. The economy cannot function as an autonomous sphere detached from the national interest, nor as a tool for extracting profits for entities operating outside the political community. Leaving key sectors to the logic of an unlimited market leads to loss of control over strategic resources, dependence on external decision-making centers, and weakening of social stability.",
      "National integralism rejects both the dogma of extreme economic liberalism and collectivist socialist concepts. We stand for strong, conscious, and responsible state interventionism aimed at protecting the national interest against the dominance of international capital. The state must possess real regulatory and ownership instruments enabling control over key sectors of the economy, the financial system, infrastructure, and the labor market.",
      "Interventionism is not the negation of a rational economy, but the condition for subordinating it to the common good. Without an active role of the state, the economy becomes an instrument of political pressure, and economic decisions are made beyond the borders of the national community. Limiting the influence of international capital, countering speculation, protecting domestic production and ownership, and ensuring the economic security of society are indispensable elements of state sovereignty.",
      "A strong national state cannot abdicate responsibility for the shape of the economy. It must actively counter processes that lead to exploitation, destabilization, and the subordination of the economy to external interests. Only an economy embedded within national frameworks and subordinated to long-term goals of the community can constitute the foundation of durable political and social independence.",
      "We reject the right of any supranational structures, networks of interests, and ideological projects to interfere in the culture, education, economy, and politics of the nation-state. The state must regain full control over strategic areas of social life in order to effectively defend the national interest.",
      "The nation-state cannot remain neutral toward processes that lead to the moral, cultural, and political decay of the community. It is its duty to protect national identity, moral order, and sovereignty from pressure by the international conspiracy, regardless of the forms it takes. In international relations, we reject all mechanisms of subordination to supranational decision-making centers that seek to liquidate nation-states as real subjects of history.",
      "National integralism is a project of regaining control over our own fate. It is opposition to a world managed from behind the scenes, in which nations are to be replaced by markets, consumers, and shapeless populations. It is a call to rebuild the national community as a sovereign, conscious, and morally rooted political subject.",
    ],
  },
  de: {
    title: "Manifest",
    paragraphs: [
      "Der Liberalismus ist keine neutrale Freiheitsphilosophie, sondern ein ideologischer Schleier für eine internationale Verschwörung gegen die Nationen und ihre Souveränität. Unter den Parolen von Pluralismus, Offenheit und Individualrechten wurde eine beispiellose Übernahme realer Macht über die Staaten durch Strukturen vollzogen, denen Verwurzelung, Verantwortung und Loyalität gegenüber irgendeiner nationalen Gemeinschaft fehlen. Wir leben in einer Epoche fortschreitender moralischer Desorganisation, in der der Bruch mit der natürlichen und historischen Ordnung zur Norm geworden ist und nicht zur Ausnahme. Dieser Zustand ist das Ergebnis eines langfristigen und koordinierten Prozesses der Schwächung der Nationen.",
      "Die heutige Welt steht unter dem Einfluss einer internationalen kapital‑ideologischen Verschwörung, gebildet durch globale Finanzfonds, Medienstrukturen, „Experten“-Organisationen, Stiftungen sowie supranationale Institutionen, die außerhalb der demokratischen Kontrolle der Gesellschaften agieren. Diese Verschwörung funktioniert nicht als eine einheitliche Institution, sondern als ein Netzwerk von Interessen, dessen Ziel es ist, Nationalstaaten der Logik globaler Steuerung und des Profits zu unterwerfen. Nationen sollen zu verwalteten Massen herabgesetzt werden, denen realer Einfluss auf ihr eigenes Schicksal fehlt.",
      "Einer der zentralen Wirkungsbereiche dieser Verschwörung ist die Kultur. Kunst ist nicht länger Ausdruck des Geistes der Nation, ihrer Geschichte und Erfahrung. Sie wurde von ausländischen Zentren der Finanzierung, Distribution und Legitimierung übernommen, die darüber entscheiden, was gefördert, ausgezeichnet und im öffentlichen Raum präsent sein soll. Was heute als „Kultur“ bezeichnet wird, entspringt immer weniger dem nationalen Erbe und dient immer stärker als Träger fremder Ideologien und Muster, deren Zweck die Entwurzelung der Gesellschaft von ihrer eigenen Identität ist. Unsere Kunst ist nicht mehr unsere – sie ist importiert, aufgezwungen und externen Interessen untergeordnet.",
      "Ein ebenso wichtiges Feld der Tätigkeit dieser internationalen Verschwörung ist die Bildung. Schulen, die eine erzieherische und nationenbildende Funktion erfüllen sollten, wurden in ein Instrument ideologischer Indoktrination verwandelt. Unter dem Vorwand von Modernität und weltanschaulicher Neutralität werden Kinder und Jugendliche systematisch von ihrer eigenen Tradition, Geschichte und natürlichen moralischen Normen getrennt. Lehrpläne, Unterrichtsmaterialien sowie die Ausbildung des pädagogischen Personals entstehen immer häufiger unter dem Einfluss ausländischer Organisationen und ideologischer Zentren, deren Ziel nicht das Wohl der Nation ist, sondern ihre Umgestaltung im Sinne eines globalen Projekts.",
      "Ziel dieses Prozesses ist die Hervorbringung einer Gesellschaft, die entwurzelt, identitätslos und unfähig zu Solidarität und Widerstand ist. Ein Mensch, der von Nation, Familie und Tradition gelöst ist, wird zu einem leichten Objekt wirtschaftlicher und ideologischer Kontrolle. Moralische Degeneration, Relativierung von Werten sowie der Zerfall von Autoritäten und Gemeinschaften sind keine Nebenwirkungen der Moderne, sondern Elemente, die von der internationalen Verschwörung bewusst als Werkzeuge der Dominanz genutzt werden.",
      "Ein wesentlicher Bestandteil dieses Prozesses ist die Tätigkeit einer internationalen Clique – verstanden als eine schmale Schicht miteinander verbundener finanzieller, medialer, politischer und ideologischer Eliten, die außerhalb realer gesellschaftlicher Kontrolle agieren. Diese Clique besitzt keine demokratische Legitimation und übt dennoch entscheidenden Einfluss auf die Richtungen staatlicher Politik, mediale Narrative sowie den Rahmen zulässiger öffentlicher Debatte aus. Sie legt die Grenzen dessen fest, was man denken, sagen und schaffen darf, und stigmatisiert jeden Widerstand gegen die globale Ordnung als „Extremismus“, „Rückständigkeit“ oder „Bedrohung“.",
      "Die internationale Clique bedient sich des Apparats der Massenkultur, der Bildung, der Experteninstitutionen sowie wirtschaftlicher Druckmechanismen, um den Nationen ein einheitliches zivilisatorisches Modell aufzuzwingen, das ihrer Tradition, Geschichte und ihren Interessen widerspricht. Ihr Ziel ist nicht die Zusammenarbeit zwischen Nationen, sondern ihre dauerhafte Schwächung, die Zerstörung sozialer Bindungen und die Beraubung der Fähigkeit zum selbständigen Handeln. In einer solchen Welt werden Entscheidungen außerhalb nationaler Gemeinschaften getroffen, und Verantwortung wird in undurchsichtigen Machtstrukturen aufgelöst.",
      "Der nationale Integralismus stellt eine vollständige Zurückweisung dieser Ordnung dar. Wir erkennen die Nation als höchsten politischen Wert und einzig rechtmäßiges Subjekt des öffentlichen Lebens an.",
      "Ein integraler Bestandteil der Wiedererlangung nationaler Souveränität ist der Wiederaufbau der Kontrolle über die Wirtschaft, die in der gegenwärtigen Ordnung in erheblichem Maße den Interessen internationalen Kapitals untergeordnet wurde. Die Wirtschaft kann weder als autonome Sphäre funktionieren, die vom nationalen Interesse getrennt ist, noch als Werkzeug zur Realisierung von Gewinnen für Akteure, die außerhalb der politischen Gemeinschaft agieren. Die Überlassung zentraler Sektoren der Logik eines unbegrenzten Marktes führt zum Verlust der Kontrolle über strategische Ressourcen, zur Abhängigkeit von externen Entscheidungszentren und zur Schwächung sozialer Stabilität.",
      "Der nationale Integralismus lehnt sowohl das Dogma eines extremen wirtschaftlichen Liberalismus als auch kollektivistische sozialistische Konzepte ab. Wir bekennen uns zu einem starken, bewussten und verantwortlichen staatlichen Interventionismus, dessen Ziel der Schutz des nationalen Interesses vor der Dominanz internationalen Kapitals ist. Der Staat muss über reale regulatorische und eigentumsrechtliche Instrumente verfügen, die eine Kontrolle über zentrale Wirtschaftssektoren, das Finanzsystem, die Infrastruktur sowie den Arbeitsmarkt ermöglichen.",
      "Interventionismus ist keine Verneinung einer rationalen Wirtschaft, sondern die Voraussetzung dafür, sie dem Gemeinwohl unterzuordnen. Ohne eine aktive Rolle des Staates wird die Wirtschaft zu einem Instrument politischen Drucks, und wirtschaftliche Entscheidungen fallen außerhalb der Grenzen der nationalen Gemeinschaft. Die Begrenzung des Einflusses internationalen Kapitals, die Bekämpfung von Spekulation, der Schutz inländischer Produktion und Eigentums sowie die Sicherung der wirtschaftlichen Sicherheit der Gesellschaft sind unverzichtbare Elemente staatlicher Souveränität.",
      "Ein starker Nationalstaat kann nicht von der Verantwortung für die Gestaltung der Wirtschaft zurücktreten. Er muss aktiv Prozessen entgegenwirken, die zu Ausbeutung, Destabilisierung und der Unterordnung der Wirtschaft unter externe Interessen führen. Nur eine in nationale Rahmen eingebettete Wirtschaft, die langfristigen Zielen der Gemeinschaft untergeordnet ist, kann das Fundament dauerhafter politischer und sozialer Unabhängigkeit bilden.",
      "Wir weisen das Recht jeglicher supranationaler Strukturen, Interessennetzwerke und ideologischer Projekte zurück, in Kultur, Bildung, Wirtschaft und Politik des Nationalstaates einzugreifen. Der Staat muss die volle Kontrolle über strategische Bereiche des gesellschaftlichen Lebens zurückgewinnen, um das nationale Interesse wirksam zu verteidigen.",
      "Der Nationalstaat kann gegenüber Prozessen, die zum moralischen, kulturellen und politischen Zerfall der Gemeinschaft führen, nicht neutral bleiben. Es ist seine Pflicht, nationale Identität, moralische Ordnung und Souveränität vor dem Druck der internationalen Verschwörung zu schützen – unabhängig von den Formen, unter denen sie auftritt. In den internationalen Beziehungen lehnen wir alle Mechanismen der Unterordnung unter supranationale Entscheidungszentren ab, die darauf abzielen, Nationalstaaten als reale Subjekte der Geschichte zu liquidieren.",
      "Der nationale Integralismus ist ein Projekt, die Kontrolle über das eigene Schicksal zurückzugewinnen. Er ist ein Widerspruch gegen eine hinter den Kulissen gesteuerte Welt, in der Nationen durch Märkte, Konsumenten und gestaltlose Populationen ersetzt werden sollen. Er ist ein Aufruf zum Wiederaufbau der nationalen Gemeinschaft als souveränes, bewusstes und moralisch verwurzeltes politisches Subjekt.",
    ],
  },
};

